[pytest]
testpaths =
    CI/unit_tests
    CI/live_tests
python_files = test_*.py
python_classes = Test* *Tests
python_functions = test_*
addopts = -ra --basetemp=.pytest_tmp
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
